# Generated by Django 6.0.5 on 2026-05-28 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=50)),
                ('ssd', models.CharField(max_length=50)),
                ('processador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Manutenção', 'Manutenção'), ('Upgrade', 'Upgrade'), ('Formatação', 'Formatação'), ('Troca de peça', 'Troca de peça'), ('Outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField()),
                ('tecnico', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='computadores.computador')),
            ],
        ),
    ]
