# Generated by Django 6.0.5 on 2026-05-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='ram',
            field=models.IntegerField(help_text='Em GB'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='ssd',
            field=models.IntegerField(help_text='Em GB'),
        ),
    ]
